title: Low end code
baseURL: /
publish_mode: editorial_workflow
params:
  footer:
    content: '&copy; All rights reserved.'
    has_social: true
    links:
      - new_window: true
        text: Made with Stackbit
        url: 'https://www.stackbit.com'
  header:
    has_nav: true
    logo_img: /images/bass-clef.png
    title: "\U0001D122"
  layout_style: grid
  palette: blue
disableKinds:
  - RSS
  - taxonomy
  - taxonomyTerm
